name: check-network-config

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: new
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
          path: old
      - uses: actions/checkout@v2
        with:
          repository:  IBM/network-config-analyzer
          path: network-config-analyzer
      - uses: actions/checkout@v2
        with:
          repository: shift-left-netconfig/baseline-rules-verifier
          path: baseline-rules-verifier
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7
          architecture: x64

      - name: Install network checkers
        run: |
          python -m pip install --upgrade pip
          pip install -r  network-config-analyzer/requirements.txt
      - name: Connectivity map
        uses: docker://ghcr.io/shift-left-netconfig/nca:1.0
        with:
          args: --connectivity /github/workspace/new --pod_list /github/workspace/new/release/kubernetes-manifests.yaml --ns_list /github/workspace/new/release --pr_url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments --gh_token ${{ github.token }} --output_format md
      - name: Connectivity diff
        uses: docker://ghcr.io/shift-left-netconfig/nca:1.0
        with:
          args: --semantic_diff /github/workspace/new --base_np_list /github/workspace/old --pod_list /github/workspace/new/release/kubernetes-manifests.yaml --ns_list /github/workspace/new/release --pr_url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments --gh_token ${{ github.token }} --output_format md
      - name: Baseline requirements validation
        env:
          GHE_TOKEN: ${{ github.token }}
        run: |
          cd  ${{ github.workspace }}/new
          python ${{ github.workspace }}/baseline-rules-verifier/src/baseline_verify.py -b ${{ github.workspace }}/baseline-rules-verifier/baseline-rules/examples/restrict_access_to_payment.yaml -b ${{ github.workspace }}/baseline-rules-verifier/baseline-rules/examples/ciso_denied_ports.yaml -r release release --pr_url $GITHUB_API_URL/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments
