name: check-network-config

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: new
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
          path: old
      - name: Connectivity map
        uses: docker://ghcr.io/shift-left-netconfig/nca:1.0
        with:
          args: --connectivity /github/workspace/new --pod_list /github/workspace/new/release/kubernetes-manifests.yaml --ns_list /github/workspace/new/release --pr_url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments --gh_token ${{ github.token }} --output_format md
      - name: Connectivity diff
        uses: docker://ghcr.io/shift-left-netconfig/nca:1.0
        with:
          args: --semantic_diff /github/workspace/new --base_np_list /github/workspace/old --pod_list /github/workspace/new/release/kubernetes-manifests.yaml --ns_list /github/workspace/new/release --pr_url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments --gh_token ${{ github.token }} --output_format md
        continue-on-error: true
      - name: Baseline requirements validation
        uses: docker://ghcr.io/shift-left-netconfig/baseline-rules-verifier:1.0
        with:
          args: -b /baseline-rules-verifier/baseline-rules/examples/restrict_access_to_payment.yaml -b /baseline-rules-verifier/baseline-rules/examples/ciso_denied_ports.yaml -r /github/workspace/new/release /github/workspace/new/release --pr_url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments --tmp_dir /tmp --gh_token ${{ github.token }}
