name: network-connectivity-diff
on:
  pull_request:

jobs:
  report-netpols:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: new
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.base_ref }}
        path: old
    - name: Diff versions
      id: diff-versions
      uses: shift-left-netconfig/netpol-diff-gh-action@master
      with:
        new-path: new
        old-path: old
    - uses: actions/download-artifact@v2
      with:
        name: ${{ steps.verify-policies.outputs.diff-results-artifact }}
    - name: comment PR
      uses: machine-learning-apps/pr-comment@1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: ${{ steps.diff-versions.outputs.diff-results-file }}
