# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  pull_request:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: |
        echo "github.base_ref: ${{ github.base_ref }}"
        echo "github.head_ref: ${{ github.head_ref }}"
        echo "github.ref: ${{ github.ref }}"
        echo "github.event.number: ${{ github.event.number }}"
        echo "GITHUB_API_URL: $GITHUB_API_URL"
        echo "github.repository: ${{ github.repository }}"
        echo "url: $GITHUB_API_URL/repos/${{ github.repository }}//pulls/${{ github.event.number }}/comments"
        curl -X POST -H "Accept: application/vnd.github.v3+json" $GITHUB_API_URL/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments -d '{"body":"body"}'
