name: show-network-connectivity-graph
on:
  pull_request:

jobs:
  report-connectivity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
           fetch-depth: 0
      - name: Produce connectivity report
        id: conn-report
        uses: shift-left-netconfig/netpol-reports-gh-action@v1
        with:
          output-format: dot
      - uses: actions/download-artifact@v2
        with:
          name: ${{ steps.conn-report.outputs.conn-results-artifact }}
      - name: create png file and push to repo
        run: |
          git config user.name ${{ github.actor }}
          git config user.email '${{ github.actor }}@users.noreply.github.com'
          git checkout for_graphs
          sudo apt install graphviz
          dot -Tpng ${{ steps.conn-report.outputs.conn-results-file }} -o release/connectivity-graph.png
          git add release/connectivity-graph.png
          git commit -m"adding connectivity graph"
          git push
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: connectivity-graph
          path: release/connectivity-graph.png
