name: report-network-connectivity
on:
  workflow_dispatch:
  pull_request:

jobs:
  report-netpols:
    runs-on: ubuntu-latest
    steps:
      - uses: shift-left-netconfig/netpol-reports-gh-action@v0.2.0
