name: verify-network-policies
on:
  pull_request:

jobs:
  verify-netpols:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Verify policies
        id: verify-policies
        uses: shift-left-netconfig/netpol-verify-gh-action@v1
        with:
          corporate-policies: >
            /baseline-rules-verifier/baseline-rules/examples/ciso_denied_ports.yaml
            https://github.com/shift-left-netconfig/baseline-rules/blob/master/examples/restrict_access_to_payment.yaml
      - uses: actions/download-artifact@v2
        with:
          name: ${{ steps.verify-policies.outputs.policy-results-artifact }}
      - name: comment PR
        uses: machine-learning-apps/pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: ${{ steps.verify-policies.outputs.policy-results-file }}
      - run: exit ${{ steps.verify-policies.outputs.num-violated-policies }}
