name: verify-network-policies
on:
  pull_request:

jobs:
  verify-netpols:
    runs-on: ubuntu-latest
    steps:
      - uses: shift-left-netconfig/netpol-verify-gh-action@v0.3.0
        with:
          corporate-policies: >
            /baseline-rules-verifier/baseline-rules/examples/ciso_denied_ports.yaml
            /baseline-rules-verifier/baseline-rules/examples/restrict_access_to_payment.yaml
