name: verify-network-policies
on:
  pull_request:

jobs:
  verify-netpols:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Verify policies
        id: verify-policies
        uses: np-guard/netpol-verify-gh-action@v2
        with:
          corporate-policies: >
            /baseline-rules-verifier/baseline-rules/examples/ciso_denied_ports.yaml
            https://github.com/np-guard/baseline-rules/blob/master/examples/restrict_access_to_payment.yaml
      - uses: actions/download-artifact@v2
        with:
          name: ${{ steps.verify-policies.outputs.policy-results-artifact }}
      - name: comment PR
        run: |
          gh pr comment  ${{ github.event.number }} -F ${{ steps.verify-policies.outputs.policy-results-file }}
          exit ${{ steps.verify-policies.outputs.num-violated-policies }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
