name: verify-network-policies
on:
  workflow_dispatch:
  pull_request:

jobs:
  verify-netpols:
    runs-on: ubuntu-latest
    steps:
      - uses: shift-left-netconfig/netpol-verify-gh-action@v0.2.0
        with:
          corporate-policies: /baseline-rules-verifier/baseline-rules/examples/ciso_denied_ports.yaml
